/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: seodoaa (https://sketchfab.com/seodoaa)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/3d-glasses-5cb2d8563fd3457c9ff3b585aeabfedb
title: 3D Glasses
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
  }
  materials: {
    Bluelen1Mtl: THREE.MeshStandardMaterial
    Redlen1Mtl: THREE.MeshStandardMaterial
    Middle1Mtl: THREE.MeshStandardMaterial
  }
}

export default function Glasses({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF(
    '/models/3d_glasses/scene.gltf'
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Bluelen1Mtl}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Redlen1Mtl}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Middle1Mtl}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/3d_glasses/scene.gltf')
